{% set name = "charset-normalizer" %}
{% set version = "2.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/charset-normalizer-{{ version }}.tar.gz
  sha256: 5ec46d183433dcbd0ab716f2d7f29d8dee50505b3fdb40c6b985c7c4f5a3591f

build:
  number: 0
  noarch: python
  entry_points:
    - normalizer = charset_normalizer.cli.normalizer:cli_detect
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - charset_normalizer
    - charset_normalizer.assets
  commands:
    - pip check
    - normalizer --help
  requires:
    - pip

about:
  home: https://github.com/ousret/charset_normalizer
  summary: The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
