{% set name = "charset-normalizer" %}
{% set version = "2.0.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/charset-normalizer-{{ version }}.tar.gz
  sha256: 98398a9d69ee80548c762ba991a4728bfc3836768ed226b3945908d1a688371c

build:
  number: 0
  noarch: python
  entry_points:
    - normalizer = charset_normalizer.cli.normalizer:cli_detect
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - charset_normalizer
    - charset_normalizer.assets
  commands:
    - pip check
    - normalizer --help
  requires:
    - pip

about:
  home: https://github.com/ousret/charset_normalizer
  summary: The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
